<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BannerAdsSeeder extends Seeder
{
    public function run()
    {
        // Create Banner Categories
        $categories = [
            [
                'name' => 'Technology',
                'slug' => 'technology',
                'description' => 'Tech products and services',
                'icon' => 'microchip',
                'color' => '#3B82F6',
                'sort_order' => 1,
                'active_banners_count' => 3,
            ],
            [
                'name' => 'Fashion',
                'slug' => 'fashion',
                'description' => 'Clothing and accessories',
                'icon' => 'tshirt',
                'color' => '#EC4899',
                'sort_order' => 2,
                'active_banners_count' => 2,
            ],
            [
                'name' => 'Food & Dining',
                'slug' => 'food-dining',
                'description' => 'Restaurants and food services',
                'icon' => 'utensils',
                'color' => '#F59E0B',
                'sort_order' => 3,
                'active_banners_count' => 4,
            ],
            [
                'name' => 'Travel',
                'slug' => 'travel',
                'description' => 'Travel and tourism',
                'icon' => 'plane',
                'color' => '#10B981',
                'sort_order' => 4,
                'active_banners_count' => 2,
            ],
            [
                'name' => 'Real Estate',
                'slug' => 'real-estate',
                'description' => 'Property and real estate',
                'icon' => 'home',
                'color' => '#8B5CF6',
                'sort_order' => 5,
                'active_banners_count' => 1,
            ],
        ];

        foreach ($categories as $category) {
            DB::table('banner_categories')->insert(array_merge($category, [
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        // Create Banner Ads
        $banners = [
            [
                'banner_category_id' => 1,
                'title' => 'New iPhone 14 Pro',
                'slug' => 'iphone-14-pro-banner',
                'description' => 'The latest iPhone with advanced camera system and A16 Bionic chip',
                'business_name' => 'TechStore',
                'contact_person' => 'John Smith',
                'email' => 'john@techstore.com',
                'phone' => '+1234567890',
                'website_url' => 'https://techstore.com/iphone14',
                'business_logo' => 'banners/techstore-logo.png',
                'banner_type' => 'image',
                'banner_size' => '728x90',
                'banner_image' => 'banners/iphone-14-pro-banner.jpg',
                'destination_link' => 'https://techstore.com/iphone-14-pro',
                'call_to_action' => 'Shop Now',
                'key_selling_points' => 'Advanced camera system, A16 Bionic chip, Dynamic Island',
                'offer_details' => 'Free shipping on orders over $500',
                'validity_start' => Carbon::now()->subDays(5),
                'validity_end' => Carbon::now()->addDays(25),
                'country' => 'United States',
                'city' => 'New York',
                'target_countries' => 'USA, Canada, UK',
                'target_audience' => 'Tech enthusiasts, early adopters',
                'promotion_tier' => 'featured',
                'promotion_price' => 500.00,
                'promotion_start' => Carbon::now()->subDays(5),
                'promotion_end' => Carbon::now()->addDays(25),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 12500,
                'clicks_count' => 890,
                'approved_at' => Carbon::now()->subDays(4),
            ],
            [
                'banner_category_id' => 2,
                'title' => 'Summer Fashion Sale',
                'slug' => 'summer-fashion-sale',
                'description' => 'Up to 50% off on selected summer collection',
                'business_name' => 'Fashion Hub',
                'contact_person' => 'Sarah Johnson',
                'email' => 'sarah@fashionhub.com',
                'phone' => '+1234567891',
                'website_url' => 'https://fashionhub.com/summer-sale',
                'business_logo' => 'banners/fashionhub-logo.png',
                'banner_type' => 'image',
                'banner_size' => '300x250',
                'banner_image' => 'banners/summer-fashion-banner.jpg',
                'destination_link' => 'https://fashionhub.com/summer-sale',
                'call_to_action' => 'Shop Sale',
                'key_selling_points' => 'Up to 50% off, New arrivals, Free returns',
                'offer_details' => 'Limited time offer on selected items',
                'validity_start' => Carbon::now()->subDays(2),
                'validity_end' => Carbon::now()->addDays(15),
                'country' => 'United Kingdom',
                'city' => 'London',
                'target_countries' => 'UK, Ireland, France',
                'target_audience' => 'Fashion conscious women 18-35',
                'promotion_tier' => 'promoted',
                'promotion_price' => 300.00,
                'promotion_start' => Carbon::now()->subDays(2),
                'promotion_end' => Carbon::now()->addDays(15),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 8900,
                'clicks_count' => 567,
                'approved_at' => Carbon::now()->subDays(1),
            ],
            [
                'banner_category_id' => 3,
                'title' => 'Premium Restaurant Experience',
                'slug' => 'premium-restaurant',
                'description' => 'Fine dining at its best with world-class cuisine',
                'business_name' => 'Le Gourmet',
                'contact_person' => 'Chef Michel',
                'email' => 'michel@legourmet.com',
                'phone' => '+1234567892',
                'website_url' => 'https://legourmet.com',
                'business_logo' => 'banners/legourmet-logo.png',
                'banner_type' => 'image',
                'banner_size' => '300x250',
                'banner_image' => 'banners/legourmet-banner.jpg',
                'destination_link' => 'https://legourmet.com/reservations',
                'call_to_action' => 'Book Table',
                'key_selling_points' => 'Michelin star, Fresh ingredients, Exceptional service',
                'offer_details' => 'Complimentary wine with dinner for two',
                'validity_start' => Carbon::now(),
                'validity_end' => Carbon::now()->addDays(30),
                'country' => 'France',
                'city' => 'Paris',
                'target_countries' => 'France, Belgium, Luxembourg',
                'target_audience' => 'Fine dining enthusiasts, Special occasions',
                'promotion_tier' => 'sponsored',
                'promotion_price' => 750.00,
                'promotion_start' => Carbon::now(),
                'promotion_end' => Carbon::now()->addDays(30),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 5600,
                'clicks_count' => 234,
                'approved_at' => Carbon::now()->subHours(6),
            ],
            [
                'banner_category_id' => 4,
                'title' => 'Dream Vacation Package',
                'slug' => 'dream-vacation',
                'description' => 'All-inclusive tropical paradise getaway',
                'business_name' => 'Paradise Tours',
                'contact_person' => 'Maria Garcia',
                'email' => 'maria@paradisetours.com',
                'phone' => '+1234567893',
                'website_url' => 'https://paradisetours.com/dream-vacation',
                'business_logo' => 'banners/paradise-tours-logo.png',
                'banner_type' => 'image',
                'banner_size' => '728x90',
                'banner_image' => 'banners/dream-vacation-banner.jpg',
                'destination_link' => 'https://paradisetours.com/dream-vacation',
                'call_to_action' => 'Book Now',
                'key_selling_points' => 'All-inclusive, Beachfront resort, Free flights',
                'offer_details' => 'Early bird discount - Save 20%',
                'validity_start' => Carbon::now()->addDays(1),
                'validity_end' => Carbon::now()->addDays(45),
                'country' => 'Spain',
                'city' => 'Barcelona',
                'target_countries' => 'Spain, Portugal, Italy',
                'target_audience' => 'Couples, Families, Holiday seekers',
                'promotion_tier' => 'standard',
                'promotion_price' => 200.00,
                'promotion_start' => Carbon::now()->addDays(1),
                'promotion_end' => Carbon::now()->addDays(45),
                'is_verified_business' => true,
                'status' => 'pending',
                'is_active' => true,
                'views_count' => 3200,
                'clicks_count' => 145,
            ],
            [
                'banner_category_id' => 5,
                'title' => 'Luxury Apartments for Sale',
                'slug' => 'luxury-apartments',
                'description' => 'Premium residential properties in prime locations',
                'business_name' => 'Elite Properties',
                'contact_person' => 'Robert Chen',
                'email' => 'robert@eliteproperties.com',
                'phone' => '+1234567894',
                'website_url' => 'https://eliteproperties.com/luxury',
                'business_logo' => 'banners/elite-properties-logo.png',
                'banner_type' => 'image',
                'banner_size' => '300x250',
                'banner_image' => 'banners/luxury-apartments-banner.jpg',
                'destination_link' => 'https://eliteproperties.com/luxury',
                'call_to_action' => 'View Properties',
                'key_selling_points' => 'Prime locations, Luxury amenities, Investment opportunity',
                'offer_details' => 'Zero down payment available',
                'validity_start' => Carbon::now()->subDays(10),
                'validity_end' => Carbon::now()->addDays(20),
                'country' => 'United Arab Emirates',
                'city' => 'Dubai',
                'target_countries' => 'UAE, Saudi Arabia, Qatar',
                'target_audience' => 'High net worth individuals, Investors',
                'promotion_tier' => 'network_boost',
                'promotion_price' => 1000.00,
                'promotion_start' => Carbon::now()->subDays(10),
                'promotion_end' => Carbon::now()->addDays(20),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 8900,
                'clicks_count' => 445,
                'approved_at' => Carbon::now()->subDays(8),
            ],
        ];

        foreach ($banners as $banner) {
            DB::table('banner_ads')->insert(array_merge($banner, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('Banner Ads seeder completed successfully!');
    }
}
