<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BannerAd;
use App\Models\BannerCategory;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BannerAdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing banner ads
        DB::table('banner_ads')->delete();

        $categories = BannerCategory::pluck('id')->toArray();
        $users = User::pluck('user_id')->toArray();

        if (empty($categories) || empty($users)) {
            $this->command->warn('No categories or users found. Please run other seeders first.');
            return;
        }

        $bannerAds = [
            [
                'title' => 'Luxury Properties - Premium Real Estate',
                'description' => 'Discover exclusive luxury properties in prime locations. Premium homes, apartments, and villas for discerning buyers.',
                'business_name' => 'Elite Properties Inc',
                'contact_person' => 'John Davidson',
                'email' => 'john@eliteproperties.com',
                'phone' => '+1-555-123-4567',
                'website_url' => 'https://eliteproperties.com',
                'business_logo' => 'elite-properties-logo.png',
                'banner_type' => 'image',
                'banner_size' => '728x90',
                'banner_image' => 'luxury-real-estate-banner.jpg',
                'destination_link' => 'https://eliteproperties.com/luxury-collection',
                'call_to_action' => 'View Properties',
                'key_selling_points' => '5-star amenities, prime locations, investment opportunities',
                'offer_details' => 'Limited time offer: Free property valuation with every viewing',
                'validity_start' => now()->subDays(10),
                'validity_end' => now()->addDays(20),
                'banner_category_id' => $categories[0] ?? 1, // Real Estate
                'country' => 'USA',
                'city' => 'New York',
                'target_countries' => json_encode(['USA', 'Canada', 'UK']),
                'target_audience' => json_encode(['High-net-worth individuals', 'Investors', 'Property developers']),
                'promotion_tier' => 'sponsored',
                'promotion_price' => 200.00,
                'promotion_start' => now()->subDays(5),
                'promotion_end' => now()->addDays(25),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 15420,
                'clicks_count' => 892,
                'approved_at' => now()->subDays(6),
                'user_id' => $users[0] ?? 1,
            ],
            [
                'title' => 'Premium Car Dealership - Best Deals 2024',
                'description' => 'New and certified pre-owned vehicles at unbeatable prices. Quality cars, financing available.',
                'business_name' => 'AutoMax Dealership',
                'contact_person' => 'Sarah Johnson',
                'email' => 'sarah@automax.com',
                'phone' => '+1-555-987-6543',
                'website_url' => 'https://automax.com',
                'business_logo' => 'automax-logo.png',
                'banner_type' => 'image',
                'banner_size' => '300x250',
                'banner_image' => 'car-dealership-banner.jpg',
                'destination_link' => 'https://automax.com/special-offers',
                'call_to_action' => 'Browse Inventory',
                'key_selling_points' => '0% financing available, certified vehicles, warranty included',
                'offer_details' => 'Summer Sale: Up to $5,000 cash back on select models',
                'validity_start' => now()->subDays(15),
                'validity_end' => now()->addDays(15),
                'banner_category_id' => $categories[1] ?? 2, // Vehicles
                'country' => 'USA',
                'city' => 'Los Angeles',
                'target_countries' => json_encode(['USA', 'Canada']),
                'target_audience' => json_encode(['Car buyers', 'Families', 'Business owners']),
                'promotion_tier' => 'featured',
                'promotion_price' => 100.00,
                'promotion_start' => now()->subDays(10),
                'promotion_end' => now()->addDays(20),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 8750,
                'clicks_count' => 423,
                'approved_at' => now()->subDays(11),
                'user_id' => $users[1] ?? 2,
            ],
            [
                'title' => 'Dream Vacation Package - Tropical Paradise',
                'description' => 'All-inclusive tropical vacation packages. Beach resorts, spa treatments, and adventure activities.',
                'business_name' => 'Paradise Travel Co',
                'contact_person' => 'Maria Rodriguez',
                'email' => 'maria@paradisetravel.com',
                'phone' => '+1-555-456-7890',
                'website_url' => 'https://paradisetravel.com',
                'business_logo' => 'paradise-travel-logo.png',
                'banner_type' => 'animated',
                'banner_size' => '728x90',
                'banner_image' => 'tropical-vacation-banner.gif',
                'destination_link' => 'https://paradisetravel.com/tropical-deals',
                'call_to_action' => 'Book Now',
                'key_selling_points' => 'All-inclusive packages, luxury resorts, expert guides',
                'offer_details' => 'Early bird discount: 20% off bookings made 30 days in advance',
                'validity_start' => now()->subDays(5),
                'validity_end' => now()->addDays(25),
                'banner_category_id' => $categories[2] ?? 3, // Travel & Resorts
                'country' => 'USA',
                'city' => 'Miami',
                'target_countries' => json_encode(['USA', 'Canada', 'Mexico', 'Caribbean']),
                'target_audience' => json_encode(['Vacationers', 'Honeymooners', 'Families']),
                'promotion_tier' => 'promoted',
                'promotion_price' => 50.00,
                'promotion_start' => now()->subDays(3),
                'promotion_end' => now()->addDays(27),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 12350,
                'clicks_count' => 678,
                'approved_at' => now()->subDays(4),
                'user_id' => $users[2] ?? 3,
            ],
            [
                'title' => 'Tech Solutions - Cloud Computing Services',
                'description' => 'Professional cloud computing and IT solutions for businesses. Scalable, secure, and reliable.',
                'business_name' => 'CloudTech Solutions',
                'contact_person' => 'David Chen',
                'email' => 'david@cloudtech.com',
                'phone' => '+1-555-234-5678',
                'website_url' => 'https://cloudtech.com',
                'business_logo' => 'cloudtech-logo.png',
                'banner_type' => 'html5',
                'banner_size' => '300x250',
                'banner_image' => 'cloud-computing-banner.zip',
                'destination_link' => 'https://cloudtech.com/services',
                'call_to_action' => 'Get Started',
                'key_selling_points' => '99.9% uptime, 24/7 support, scalable solutions',
                'offer_details' => 'Free migration service for new enterprise clients',
                'validity_start' => now()->subDays(8),
                'validity_end' => now()->addDays(22),
                'banner_category_id' => $categories[9] ?? 10, // Tech & Electronics
                'country' => 'USA',
                'city' => 'San Francisco',
                'target_countries' => json_encode(['USA', 'Canada', 'UK', 'Germany']),
                'target_audience' => json_encode(['IT managers', 'Business owners', 'Startups']),
                'promotion_tier' => 'featured',
                'promotion_price' => 100.00,
                'promotion_start' => now()->subDays(7),
                'promotion_end' => now()->addDays(23),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 6230,
                'clicks_count' => 289,
                'approved_at' => now()->subDays(8),
                'user_id' => $users[3] ?? 4,
            ],
            [
                'title' => 'Fashion Boutique - Latest Collection 2024',
                'description' => 'Trendy fashion and accessories for the modern individual. Quality clothing at affordable prices.',
                'business_name' => 'Style Haven Boutique',
                'contact_person' => 'Emma Wilson',
                'email' => 'emma@stylehaven.com',
                'phone' => '+1-555-345-6789',
                'website_url' => 'https://stylehaven.com',
                'business_logo' => 'stylehaven-logo.png',
                'banner_type' => 'image',
                'banner_size' => '160x600',
                'banner_image' => 'fashion-boutique-banner.jpg',
                'destination_link' => 'https://stylehaven.com/new-collection',
                'call_to_action' => 'Shop Now',
                'key_selling_points' => 'Designer brands, free shipping, easy returns',
                'offer_details' => 'New customer discount: 15% off first purchase',
                'validity_start' => now()->subDays(12),
                'validity_end' => now()->addDays(18),
                'banner_category_id' => $categories[8] ?? 9, // Fashion & Beauty
                'country' => 'USA',
                'city' => 'New York',
                'target_countries' => json_encode(['USA', 'Canada', 'UK']),
                'target_audience' => json_encode(['Fashion enthusiasts', 'Young adults', 'Online shoppers']),
                'promotion_tier' => 'standard',
                'promotion_price' => 0.00,
                'is_verified_business' => false,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 3450,
                'clicks_count' => 156,
                'approved_at' => now()->subDays(13),
                'user_id' => $users[4] ?? 5,
            ],
            [
                'title' => 'Professional Business Consulting Services',
                'description' => 'Expert business consulting to help your company grow. Strategy, operations, and management consulting.',
                'business_name' => 'Growth Partners Consulting',
                'contact_person' => 'Michael Thompson',
                'email' => 'michael@growthpartners.com',
                'phone' => '+1-555-567-8901',
                'website_url' => 'https://growthpartners.com',
                'business_logo' => 'growthpartners-logo.png',
                'banner_type' => 'image',
                'banner_size' => '970x250',
                'banner_image' => 'business-consulting-banner.jpg',
                'destination_link' => 'https://growthpartners.com/services',
                'call_to_action' => 'Schedule Consultation',
                'key_selling_points' => 'Experienced consultants, proven results, customized solutions',
                'offer_details' => 'Free initial business assessment for new clients',
                'validity_start' => now()->subDays(20),
                'validity_end' => now()->addDays(10),
                'banner_category_id' => $categories[10] ?? 11, // Business & Finance
                'country' => 'USA',
                'city' => 'Chicago',
                'target_countries' => json_encode(['USA', 'Canada', 'UK', 'Australia']),
                'target_audience' => json_encode(['Business owners', 'CEOs', 'Managers']),
                'promotion_tier' => 'network_boost',
                'promotion_price' => 500.00,
                'promotion_start' => now()->subDays(15),
                'promotion_end' => now()->addDays(15),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 18760,
                'clicks_count' => 945,
                'approved_at' => now()->subDays(16),
                'user_id' => $users[0] ?? 1,
            ],
            [
                'title' => 'Gourmet Food Delivery - Restaurant Quality',
                'description' => 'Premium food delivery service featuring top local restaurants. Fast, fresh, and delicious.',
                'business_name' => 'FoodExpress Delivery',
                'contact_person' => 'Lisa Anderson',
                'email' => 'lisa@foodexpress.com',
                'phone' => '+1-555-678-9012',
                'website_url' => 'https://foodexpress.com',
                'business_logo' => 'foodexpress-logo.png',
                'banner_type' => 'video',
                'banner_size' => '300x250',
                'banner_image' => 'food-delivery-banner.mp4',
                'destination_link' => 'https://foodexpress.com/restaurants',
                'call_to_action' => 'Order Now',
                'key_selling_points' => '30-minute delivery, top restaurants, contactless delivery',
                'offer_details' => 'First order: Free delivery + 10% discount',
                'validity_start' => now()->subDays(6),
                'validity_end' => now()->addDays(24),
                'banner_category_id' => $categories[7] ?? 8, // Food & Hospitality
                'country' => 'USA',
                'city' => 'Seattle',
                'target_countries' => json_encode(['USA', 'Canada']),
                'target_audience' => json_encode(['Food lovers', 'Busy professionals', 'Families']),
                'promotion_tier' => 'promoted',
                'promotion_price' => 50.00,
                'promotion_start' => now()->subDays(4),
                'promotion_end' => now()->addDays(26),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 9870,
                'clicks_count' => 534,
                'approved_at' => now()->subDays(5),
                'user_id' => $users[1] ?? 2,
            ],
            [
                'title' => 'Online Education Platform - Learn Anything',
                'description' => 'Comprehensive online courses and professional development. Learn from industry experts.',
                'business_name' => 'EduMaster Academy',
                'contact_person' => 'Dr. Robert Lee',
                'email' => 'robert@edumaster.com',
                'phone' => '+1-555-789-0123',
                'website_url' => 'https://edumaster.com',
                'business_logo' => 'edumaster-logo.png',
                'banner_type' => 'image',
                'banner_size' => '728x90',
                'banner_image' => 'online-education-banner.jpg',
                'destination_link' => 'https://edumaster.com/courses',
                'call_to_action' => 'Start Learning',
                'key_selling_points' => 'Expert instructors, flexible schedules, certificates',
                'offer_details' => 'Enrollment special: Buy one course, get one 50% off',
                'validity_start' => now()->subDays(18),
                'validity_end' => now()->addDays(12),
                'banner_category_id' => $categories[5] ?? 6, // Education
                'country' => 'USA',
                'city' => 'Boston',
                'target_countries' => json_encode(['USA', 'Canada', 'UK', 'India', 'Australia']),
                'target_audience' => json_encode(['Students', 'Professionals', 'Lifelong learners']),
                'promotion_tier' => 'featured',
                'promotion_price' => 100.00,
                'promotion_start' => now()->subDays(14),
                'promotion_end' => now()->addDays(16),
                'is_verified_business' => true,
                'status' => 'active',
                'is_active' => true,
                'views_count' => 7230,
                'clicks_count' => 412,
                'approved_at' => now()->subDays(15),
                'user_id' => $users[2] ?? 3,
            ],
        ];

        foreach ($bannerAds as $bannerData) {
            // Generate unique slug
            $bannerData['slug'] = Str::slug($bannerData['title']) . '-' . time() . rand(1000, 9999);
            
            BannerAd::create($bannerData);
        }

        $this->command->info('Banner ads seeded successfully!');
    }
}
