<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PromotedAdvert;
use App\Models\PromotedAdvertCategory;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PromotedAdvertSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create categories
        $categories = [
            [
                'name' => 'Property',
                'slug' => 'property',
                'description' => 'Real estate and property listings',
                'icon' => 'heroicon-o-home',
                'color' => '#3B82F6',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Vehicles',
                'slug' => 'vehicles',
                'description' => 'Cars, motorcycles, and other vehicles',
                'icon' => 'heroicon-o-truck',
                'color' => '#10B981',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Jobs & Services',
                'slug' => 'jobs-services',
                'description' => 'Job vacancies and professional services',
                'icon' => 'heroicon-o-briefcase',
                'color' => '#F59E0B',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Business Opportunities',
                'slug' => 'business-opportunities',
                'description' => 'Business and investment opportunities',
                'icon' => 'heroicon-o-chart-bar',
                'color' => '#8B5CF6',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Electronics',
                'slug' => 'electronics',
                'description' => 'Electronic devices and gadgets',
                'icon' => 'heroicon-o-cpu-chip',
                'color' => '#EF4444',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Fashion & Beauty',
                'slug' => 'fashion-beauty',
                'description' => 'Fashion items and beauty products',
                'icon' => 'heroicon-o-sparkles',
                'color' => '#EC4899',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Travel & Experiences',
                'slug' => 'travel-experiences',
                'description' => 'Travel packages and unique experiences',
                'icon' => 'heroicon-o-globe-americas',
                'color' => '#06B6D4',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Events & Tickets',
                'slug' => 'events-tickets',
                'description' => 'Event tickets and entertainment',
                'icon' => 'heroicon-o-ticket',
                'color' => '#F97316',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Home & Garden',
                'slug' => 'home-garden',
                'description' => 'Home furniture and garden supplies',
                'icon' => 'heroicon-o-home-modern',
                'color' => '#059669',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Education & Courses',
                'slug' => 'education-courses',
                'description' => 'Educational services and courses',
                'icon' => 'heroicon-o-academic-cap',
                'color' => '#7C3AED',
                'is_active' => true,
                'sort_order' => 10,
            ],
        ];

        foreach ($categories as $category) {
            PromotedAdvertCategory::create($category);
        }

        // Get a user for testing
        $user = User::first() ?: User::factory()->create();

        // Sample promoted adverts
        $sampleAdverts = [
            [
                'title' => 'Luxury Downtown Apartment with City Views',
                'tagline' => 'Modern living in the heart of the city',
                'description' => 'Stunning 2-bedroom apartment in prime downtown location. Features panoramic city views, modern appliances, and premium finishes throughout.',
                'key_features' => json_encode([
                    '2 bedrooms, 2 bathrooms',
                    'Floor-to-ceiling windows',
                    'Modern kitchen with island',
                    'Rooftop terrace access',
                    'Gym and pool facilities',
                    '24/7 concierge service'
                ]),
                'advert_type' => 'property',
                'category_id' => 1,
                'country' => 'United Kingdom',
                'city' => 'London',
                'price' => 850000.00,
                'currency' => 'GBP',
                'price_type' => 'fixed',
                'condition' => 'new',
                'main_image' => 'luxury-apartment.jpg',
                'additional_images' => json_encode(['apartment-1.jpg', 'apartment-2.jpg', 'apartment-3.jpg']),
                'seller_name' => 'Premium Properties Ltd',
                'business_name' => 'Premium Properties Ltd',
                'phone' => '+44 20 7123 4567',
                'email' => 'info@premiumproperties.co.uk',
                'website' => 'https://premiumproperties.co.uk',
                'logo' => 'premium-logo.png',
                'verified_seller' => true,
                'promotion_tier' => 'network_wide_boost',
                'promotion_price' => 199.99,
                'promotion_start' => now()->subDays(5),
                'promotion_end' => now()->addDays(25),
                'views_count' => 1250,
                'saves_count' => 89,
                'clicks_count' => 156,
                'inquiries_count' => 23,
                'status' => 'active',
                'is_active' => true,
                'is_featured' => true,
                'approved_at' => now()->subDays(6),
                'user_id' => $user->id,
            ],
            [
                'title' => '2023 Tesla Model 3 Performance',
                'tagline' => 'Electric excellence meets performance',
                'description' => 'Like-new 2023 Tesla Model 3 Performance with autopilot, premium interior, and full warranty. Only 5,000 miles driven.',
                'key_features' => json_encode([
                    '0-60 mph in 3.1 seconds',
                    'Autopilot capability',
                    'Premium audio system',
                    'Full self-driving computer',
                    '19" Performance wheels',
                    'Carbon fiber spoiler'
                ]),
                'advert_type' => 'vehicle',
                'category_id' => 2,
                'country' => 'United States',
                'city' => 'San Francisco',
                'price' => 58999.00,
                'currency' => 'USD',
                'price_type' => 'negotiable',
                'condition' => 'used',
                'main_image' => 'tesla-model3.jpg',
                'additional_images' => json_encode(['tesla-1.jpg', 'tesla-2.jpg', 'tesla-3.jpg', 'tesla-4.jpg']),
                'seller_name' => 'John Smith',
                'phone' => '+1 415-555-0123',
                'email' => 'john.smith@email.com',
                'verified_seller' => false,
                'promotion_tier' => 'promoted_plus',
                'promotion_price' => 59.99,
                'promotion_start' => now()->subDays(3),
                'promotion_end' => now()->addDays(27),
                'views_count' => 892,
                'saves_count' => 67,
                'clicks_count' => 124,
                'inquiries_count' => 18,
                'status' => 'active',
                'is_active' => true,
                'is_featured' => false,
                'approved_at' => now()->subDays(4),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Senior Software Engineer - Remote',
                'tagline' => 'Join our innovative tech team',
                'description' => 'Exciting opportunity for experienced software engineer to join growing remote-first company. Competitive salary and benefits package.',
                'key_features' => json_encode([
                    'Fully remote position',
                    'Competitive salary ($120k-$180k)',
                    'Comprehensive health benefits',
                    'Stock options',
                    'Flexible working hours',
                    'Professional development budget'
                ]),
                'advert_type' => 'job',
                'category_id' => 3,
                'country' => 'United States',
                'city' => 'Remote',
                'price' => null,
                'currency' => 'USD',
                'price_type' => 'negotiable',
                'condition' => 'not_applicable',
                'main_image' => 'tech-job.jpg',
                'seller_name' => 'Tech Innovations Inc',
                'business_name' => 'Tech Innovations Inc',
                'phone' => '+1 555-010-2000',
                'email' => 'careers@techinnovations.com',
                'website' => 'https://techinnovations.com',
                'logo' => 'tech-logo.png',
                'verified_seller' => true,
                'promotion_tier' => 'promoted_premium',
                'promotion_price' => 99.99,
                'promotion_start' => now()->subDays(7),
                'promotion_end' => now()->addDays(23),
                'views_count' => 2103,
                'saves_count' => 156,
                'clicks_count' => 289,
                'inquiries_count' => 45,
                'status' => 'active',
                'is_active' => true,
                'is_featured' => true,
                'approved_at' => now()->subDays(8),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Profitable E-commerce Business',
                'tagline' => 'Established online store with steady revenue',
                'description' => 'Turnkey e-commerce business specializing in home decor products. Established customer base and supplier relationships.',
                'key_features' => json_encode([
                    '$250K+ annual revenue',
                    '35% profit margin',
                    '10,000+ email subscribers',
                    'Established supplier network',
                    'Social media presence',
                    'Training and support included'
                ]),
                'advert_type' => 'business',
                'category_id' => 4,
                'country' => 'Canada',
                'city' => 'Toronto',
                'price' => 75000.00,
                'currency' => 'CAD',
                'price_type' => 'negotiable',
                'condition' => 'not_applicable',
                'main_image' => 'ecommerce-business.jpg',
                'additional_images' => json_encode(['business-1.jpg', 'business-2.jpg']),
                'seller_name' => 'Business Brokers Canada',
                'business_name' => 'Business Brokers Canada',
                'phone' => '+1 416-555-7890',
                'email' => 'info@businessbrokers.ca',
                'website' => 'https://businessbrokers.ca',
                'logo' => 'broker-logo.png',
                'verified_seller' => true,
                'promotion_tier' => 'promoted_basic',
                'promotion_price' => 29.99,
                'promotion_start' => now()->subDays(2),
                'promotion_end' => now()->addDays(28),
                'views_count' => 567,
                'saves_count' => 34,
                'clicks_count' => 89,
                'inquiries_count' => 12,
                'status' => 'active',
                'is_active' => true,
                'is_featured' => false,
                'approved_at' => now()->subDays(3),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Professional Photography Services',
                'tagline' => 'Capturing your special moments',
                'description' => 'Award-winning photographer specializing in weddings, portraits, and commercial photography. Serving the greater London area.',
                'key_features' => json_encode([
                    '10+ years experience',
                    'Award-winning portfolio',
                    'Same-day preview delivery',
                    'Professional editing',
                    'Flexible packages',
                    'Indoor and outdoor shoots'
                ]),
                'advert_type' => 'service',
                'category_id' => 3,
                'country' => 'United Kingdom',
                'city' => 'London',
                'price' => 1500.00,
                'currency' => 'GBP',
                'price_type' => 'negotiable',
                'condition' => 'not_applicable',
                'main_image' => 'photography-service.jpg',
                'additional_images' => json_encode(['photo-1.jpg', 'photo-2.jpg', 'photo-3.jpg', 'photo-4.jpg', 'photo-5.jpg']),
                'seller_name' => 'Sarah Johnson',
                'business_name' => 'Sarah Johnson Photography',
                'phone' => '+44 20 7890 1234',
                'email' => 'sarah@sarahjohnsonphoto.com',
                'website' => 'https://sarahjohnsonphoto.com',
                'logo' => 'sarah-logo.png',
                'verified_seller' => true,
                'promotion_tier' => 'promoted_plus',
                'promotion_price' => 59.99,
                'promotion_start' => now()->subDays(4),
                'promotion_end' => now()->addDays(26),
                'views_count' => 1234,
                'saves_count' => 78,
                'clicks_count' => 167,
                'inquiries_count' => 29,
                'status' => 'active',
                'is_active' => true,
                'is_featured' => true,
                'approved_at' => now()->subDays(5),
                'user_id' => $user->id,
            ],
            [
                'title' => 'iPhone 15 Pro Max 256GB',
                'tagline' => 'Latest Apple technology in your hands',
                'description' => 'Brand new iPhone 15 Pro Max 256GB in Natural Titanium. Sealed in box with full warranty. Latest model with titanium design.',
                'key_features' => json_encode([
                    '256GB storage',
                    'Natural Titanium finish',
                    'A17 Pro chip',
                    'Pro camera system',
                    'Action button',
                    'USB-C connectivity'
                ]),
                'advert_type' => 'product',
                'category_id' => 5,
                'country' => 'Australia',
                'city' => 'Sydney',
                'price' => 1899.00,
                'currency' => 'AUD',
                'price_type' => 'fixed',
                'condition' => 'new',
                'main_image' => 'iphone15pro.jpg',
                'additional_images' => json_encode(['iphone-1.jpg', 'iphone-2.jpg', 'iphone-3.jpg']),
                'seller_name' => 'Tech Store Sydney',
                'business_name' => 'Tech Store Sydney',
                'phone' => '+61 2 9876 5432',
                'email' => 'sales@techstoresydney.com.au',
                'website' => 'https://techstoresydney.com.au',
                'logo' => 'techstore-logo.png',
                'verified_seller' => true,
                'promotion_tier' => 'promoted_premium',
                'promotion_price' => 99.99,
                'promotion_start' => now()->subDays(1),
                'promotion_end' => now()->addDays(29),
                'views_count' => 3456,
                'saves_count' => 234,
                'clicks_count' => 567,
                'inquiries_count' => 89,
                'status' => 'active',
                'is_active' => true,
                'is_featured' => true,
                'approved_at' => now()->subDays(2),
                'user_id' => $user->id,
            ],
        ];

        foreach ($sampleAdverts as $advert) {
            $advert['slug'] = Str::slug($advert['title']);
            PromotedAdvert::create($advert);
        }

        $this->command->info('Promoted adverts seeded successfully!');
    }
}
