-- Create promoted_adverts table
CREATE TABLE `promoted_adverts` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL,
    `slug` varchar(255) NOT NULL,
    `tagline` varchar(255) DEFAULT NULL,
    `description` text NOT NULL,
    `key_features` json DEFAULT NULL,
    `special_notes` text DEFAULT NULL,
    `advert_type` varchar(255) NOT NULL,
    `category_id` bigint unsigned DEFAULT NULL,
    `country` varchar(100) NOT NULL,
    `city` varchar(100) DEFAULT NULL,
    `latitude` decimal(10,8) DEFAULT NULL,
    `longitude` decimal(11,8) DEFAULT NULL,
    `location_privacy` enum('exact','approximate') DEFAULT 'exact',
    `price` decimal(12,2) DEFAULT NULL,
    `currency` varchar(3) DEFAULT 'GBP',
    `price_type` enum('fixed','negotiable','free') DEFAULT 'fixed',
    `condition` enum('new','used','not_applicable') DEFAULT NULL,
    `main_image` varchar(255) NOT NULL,
    `additional_images` json DEFAULT NULL,
    `video_link` varchar(255) DEFAULT NULL,
    `seller_name` varchar(255) NOT NULL,
    `business_name` varchar(255) DEFAULT NULL,
    `phone` varchar(20) NOT NULL,
    `email` varchar(255) NOT NULL,
    `website` varchar(255) DEFAULT NULL,
    `social_links` json DEFAULT NULL,
    `logo` varchar(255) DEFAULT NULL,
    `verified_seller` tinyint(1) DEFAULT 0,
    `promotion_tier` enum('promoted_basic','promoted_plus','promoted_premium','network_wide_boost') DEFAULT 'promoted_basic',
    `promotion_price` decimal(10,2) DEFAULT 0.00,
    `promotion_start` date DEFAULT NULL,
    `promotion_end` date DEFAULT NULL,
    `views_count` int DEFAULT 0,
    `saves_count` int DEFAULT 0,
    `clicks_count` int DEFAULT 0,
    `inquiries_count` int DEFAULT 0,
    `status` enum('draft','pending','active','rejected','expired') DEFAULT 'draft',
    `is_active` tinyint(1) DEFAULT 1,
    `is_featured` tinyint(1) DEFAULT 0,
    `approved_at` timestamp NULL DEFAULT NULL,
    `user_id` bigint unsigned DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `promoted_adverts_slug_unique` (`slug`),
    KEY `promoted_adverts_status_is_active_index` (`status`,`is_active`),
    KEY `promoted_adverts_promotion_tier_promotion_start_promotion_end_index` (`promotion_tier`,`promotion_start`,`promotion_end`),
    KEY `promoted_adverts_advert_type_index` (`advert_type`),
    KEY `promoted_adverts_category_id_index` (`category_id`),
    KEY `promoted_adverts_country_index` (`country`),
    KEY `promoted_adverts_views_count_index` (`views_count`),
    KEY `promoted_adverts_saves_count_index` (`saves_count`),
    KEY `promoted_adverts_created_at_index` (`created_at`),
    KEY `promoted_adverts_is_featured_index` (`is_featured`),
    KEY `promoted_adverts_user_id_foreign` (`user_id`),
    CONSTRAINT `promoted_adverts_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create promoted_advert_categories table
CREATE TABLE `promoted_advert_categories` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `slug` varchar(255) NOT NULL,
    `description` text DEFAULT NULL,
    `icon` varchar(100) DEFAULT NULL,
    `color` varchar(7) DEFAULT '#3B82F6',
    `image` varchar(255) DEFAULT NULL,
    `is_active` tinyint(1) DEFAULT 1,
    `sort_order` int DEFAULT 0,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `promoted_advert_categories_slug_unique` (`slug`),
    KEY `promoted_advert_categories_is_active_sort_order_index` (`is_active`,`sort_order`),
    KEY `promoted_advert_categories_slug_index` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create promoted_advert_favorites table
CREATE TABLE `promoted_advert_favorites` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `promoted_advert_id` bigint unsigned NOT NULL,
    `user_id` bigint unsigned NOT NULL,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `unique_promoted_favorite` (`promoted_advert_id`,`user_id`),
    KEY `promoted_advert_favorites_user_id_index` (`user_id`),
    KEY `promoted_advert_favorites_promoted_advert_id_index` (`promoted_advert_id`),
    CONSTRAINT `promoted_advert_favorites_promoted_advert_id_foreign` FOREIGN KEY (`promoted_advert_id`) REFERENCES `promoted_adverts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `promoted_advert_favorites_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create promoted_advert_analytics table
CREATE TABLE `promoted_advert_analytics` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `promoted_advert_id` bigint unsigned NOT NULL,
    `event_type` varchar(255) NOT NULL,
    `ip_address` varchar(45) DEFAULT NULL,
    `user_agent` text DEFAULT NULL,
    `country` varchar(100) DEFAULT NULL,
    `city` varchar(100) DEFAULT NULL,
    `user_id` bigint unsigned DEFAULT NULL,
    `metadata` json DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `promoted_advert_analytics_promoted_advert_id_event_type_index` (`promoted_advert_id`,`event_type`),
    KEY `promoted_advert_analytics_event_type_index` (`event_type`),
    KEY `promoted_advert_analytics_created_at_index` (`created_at`),
    KEY `promoted_advert_analytics_country_index` (`country`),
    KEY `promoted_advert_analytics_promoted_advert_id_foreign` (`promoted_advert_id`),
    KEY `promoted_advert_analytics_user_id_foreign` (`user_id`),
    CONSTRAINT `promoted_advert_analytics_promoted_advert_id_foreign` FOREIGN KEY (`promoted_advert_id`) REFERENCES `promoted_adverts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `promoted_advert_analytics_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
