-- Create Resorts & Travel Categories Table
CREATE TABLE IF NOT EXISTS `resorts_travel_categories` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `slug` varchar(255) NOT NULL,
    `type` enum('accommodation','transport','experience') NOT NULL,
    `description` text NULL,
    `icon` varchar(255) NULL,
    `image` varchar(255) NULL,
    `is_active` tinyint(1) NOT NULL DEFAULT '1',
    `sort_order` int NOT NULL DEFAULT '0',
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `resorts_travel_categories_slug_unique` (`slug`),
    KEY `resorts_travel_categories_type_is_active_index` (`type`,`is_active`),
    KEY `resorts_travel_categories_sort_order_index` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create Resorts & Travel Adverts Table
CREATE TABLE IF NOT EXISTS `resorts_travel_adverts` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `user_id` bigint unsigned NOT NULL,
    `category_id` bigint unsigned NULL,
    `title` varchar(255) NOT NULL,
    `slug` varchar(255) NOT NULL,
    `tagline` varchar(255) NULL,
    `advert_type` enum('accommodation','transport','experience') NOT NULL,
    `accommodation_type` enum('resort','hotel','bnb','guest_house','holiday_home','villa','lodge') NULL,
    `transport_type` enum('airport_transfer','taxi_chauffeur','car_hire','shuttle_bus','tour_bus','boat_ferry','motorbike_scooter') NULL,
    `experience_type` enum('tours','excursions','adventure_packages','wellness_retreats') NULL,
    `country` varchar(100) NOT NULL,
    `city` varchar(100) NOT NULL,
    `address` text NULL,
    `latitude` decimal(10,8) NULL,
    `longitude` decimal(11,8) NULL,
    `price_per_night` decimal(10,2) NULL,
    `price_per_trip` decimal(10,2) NULL,
    `price_per_service` decimal(10,2) NULL,
    `currency` varchar(3) NOT NULL DEFAULT 'GBP',
    `availability_start` date NULL,
    `availability_end` date NULL,
    `room_types` json NULL,
    `amenities` json NULL,
    `distance_to_city_centre` int NULL,
    `check_in_time` time NULL,
    `check_out_time` time NULL,
    `guest_capacity` int NULL,
    `vehicle_type` varchar(100) NULL,
    `passenger_capacity` int NULL,
    `luggage_capacity` int NULL,
    `service_area` text NULL,
    `operating_hours` json NULL,
    `airport_pickup` tinyint(1) NOT NULL DEFAULT '0',
    `duration` varchar(100) NULL,
    `group_size` int NULL,
    `whats_included` text NULL,
    `what_to_bring` text NULL,
    `description` longtext NOT NULL,
    `overview` text NULL,
    `key_features` text NULL,
    `why_travellers_love_this` text NULL,
    `nearby_attractions` text NULL,
    `additional_notes` text NULL,
    `contact_name` varchar(255) NOT NULL,
    `business_name` varchar(255) NULL,
    `phone_number` varchar(20) NOT NULL,
    `email` varchar(255) NOT NULL,
    `website` varchar(255) NULL,
    `social_links` json NULL,
    `logo` varchar(255) NULL,
    `verified_business` tinyint(1) NOT NULL DEFAULT '0',
    `images` json NULL,
    `video_link` varchar(255) NULL,
    `main_image` varchar(255) NULL,
    `promotion_tier` enum('standard','promoted','featured','sponsored','network_wide') NOT NULL DEFAULT 'standard',
    `is_active` tinyint(1) NOT NULL DEFAULT '1',
    `is_approximate_location` tinyint(1) NOT NULL DEFAULT '0',
    `deleted_at` timestamp NULL DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `resorts_travel_adverts_slug_unique` (`slug`),
    KEY `resorts_travel_adverts_user_id_foreign` (`user_id`),
    KEY `resorts_travel_adverts_category_id_index` (`category_id`),
    KEY `resorts_travel_adverts_advert_type_is_active_index` (`advert_type`,`is_active`),
    KEY `resorts_travel_adverts_country_city_index` (`country`,`city`),
    KEY `resorts_travel_adverts_promotion_tier_is_active_index` (`promotion_tier`,`is_active`),
    KEY `resorts_travel_adverts_price_per_night_index` (`price_per_night`),
    KEY `resorts_travel_adverts_price_per_trip_index` (`price_per_trip`),
    KEY `resorts_travel_adverts_price_per_service_index` (`price_per_service`),
    FULLTEXT KEY `resorts_travel_adverts_title_description_tagline_fulltext` (`title`,`description`,`tagline`),
    CONSTRAINT `resorts_travel_adverts_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `ea_user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
