<?php

namespace App\Support;

/**
 * Canonical worldwide country list (ISO 3166-1) for Filament, API, and seeding.
 */
class WorldCountries
{
    /** @return array<int, array{name:string,iso_code:string,code:string,region:string}> */
    public static function all(): array
    {
        return [
            ['name' => 'Afghanistan', 'iso_code' => 'AF', 'code' => 'AFG', 'region' => 'asia'],
            ['name' => 'Albania', 'iso_code' => 'AL', 'code' => 'ALB', 'region' => 'europe'],
            ['name' => 'Algeria', 'iso_code' => 'DZ', 'code' => 'DZA', 'region' => 'africa'],
            ['name' => 'Andorra', 'iso_code' => 'AD', 'code' => 'AND', 'region' => 'europe'],
            ['name' => 'Angola', 'iso_code' => 'AO', 'code' => 'AGO', 'region' => 'africa'],
            ['name' => 'Antigua and Barbuda', 'iso_code' => 'AG', 'code' => 'ATG', 'region' => 'north-america'],
            ['name' => 'Argentina', 'iso_code' => 'AR', 'code' => 'ARG', 'region' => 'south-america'],
            ['name' => 'Armenia', 'iso_code' => 'AM', 'code' => 'ARM', 'region' => 'asia'],
            ['name' => 'Australia', 'iso_code' => 'AU', 'code' => 'AUS', 'region' => 'oceania'],
            ['name' => 'Austria', 'iso_code' => 'AT', 'code' => 'AUT', 'region' => 'europe'],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZ', 'code' => 'AZE', 'region' => 'asia'],
            ['name' => 'Bahamas', 'iso_code' => 'BS', 'code' => 'BHS', 'region' => 'north-america'],
            ['name' => 'Bahrain', 'iso_code' => 'BH', 'code' => 'BHR', 'region' => 'middle-east'],
            ['name' => 'Bangladesh', 'iso_code' => 'BD', 'code' => 'BGD', 'region' => 'asia'],
            ['name' => 'Barbados', 'iso_code' => 'BB', 'code' => 'BRB', 'region' => 'north-america'],
            ['name' => 'Belarus', 'iso_code' => 'BY', 'code' => 'BLR', 'region' => 'europe'],
            ['name' => 'Belgium', 'iso_code' => 'BE', 'code' => 'BEL', 'region' => 'europe'],
            ['name' => 'Belize', 'iso_code' => 'BZ', 'code' => 'BLZ', 'region' => 'north-america'],
            ['name' => 'Benin', 'iso_code' => 'BJ', 'code' => 'BEN', 'region' => 'africa'],
            ['name' => 'Bhutan', 'iso_code' => 'BT', 'code' => 'BTN', 'region' => 'asia'],
            ['name' => 'Bolivia', 'iso_code' => 'BO', 'code' => 'BOL', 'region' => 'south-america'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BA', 'code' => 'BIH', 'region' => 'europe'],
            ['name' => 'Botswana', 'iso_code' => 'BW', 'code' => 'BWA', 'region' => 'africa'],
            ['name' => 'Brazil', 'iso_code' => 'BR', 'code' => 'BRA', 'region' => 'south-america'],
            ['name' => 'Brunei', 'iso_code' => 'BN', 'code' => 'BRN', 'region' => 'asia'],
            ['name' => 'Bulgaria', 'iso_code' => 'BG', 'code' => 'BGR', 'region' => 'europe'],
            ['name' => 'Burkina Faso', 'iso_code' => 'BF', 'code' => 'BFA', 'region' => 'africa'],
            ['name' => 'Burundi', 'iso_code' => 'BI', 'code' => 'BDI', 'region' => 'africa'],
            ['name' => 'Cape Verde', 'iso_code' => 'CV', 'code' => 'CPV', 'region' => 'africa'],
            ['name' => 'Cambodia', 'iso_code' => 'KH', 'code' => 'KHM', 'region' => 'asia'],
            ['name' => 'Cameroon', 'iso_code' => 'CM', 'code' => 'CMR', 'region' => 'africa'],
            ['name' => 'Canada', 'iso_code' => 'CA', 'code' => 'CAN', 'region' => 'north-america'],
            ['name' => 'Central African Republic', 'iso_code' => 'CF', 'code' => 'CAF', 'region' => 'africa'],
            ['name' => 'Chad', 'iso_code' => 'TD', 'code' => 'TCD', 'region' => 'africa'],
            ['name' => 'Chile', 'iso_code' => 'CL', 'code' => 'CHL', 'region' => 'south-america'],
            ['name' => 'China', 'iso_code' => 'CN', 'code' => 'CHN', 'region' => 'asia'],
            ['name' => 'Colombia', 'iso_code' => 'CO', 'code' => 'COL', 'region' => 'south-america'],
            ['name' => 'Comoros', 'iso_code' => 'KM', 'code' => 'COM', 'region' => 'africa'],
            ['name' => 'Congo', 'iso_code' => 'CG', 'code' => 'COG', 'region' => 'africa'],
            ['name' => 'Costa Rica', 'iso_code' => 'CR', 'code' => 'CRI', 'region' => 'north-america'],
            ['name' => 'Croatia', 'iso_code' => 'HR', 'code' => 'HRV', 'region' => 'europe'],
            ['name' => 'Cuba', 'iso_code' => 'CU', 'code' => 'CUB', 'region' => 'north-america'],
            ['name' => 'Cyprus', 'iso_code' => 'CY', 'code' => 'CYP', 'region' => 'middle-east'],
            ['name' => 'Czech Republic', 'iso_code' => 'CZ', 'code' => 'CZE', 'region' => 'europe'],
            ['name' => 'Denmark', 'iso_code' => 'DK', 'code' => 'DNK', 'region' => 'europe'],
            ['name' => 'Djibouti', 'iso_code' => 'DJ', 'code' => 'DJI', 'region' => 'africa'],
            ['name' => 'Dominica', 'iso_code' => 'DM', 'code' => 'DMA', 'region' => 'north-america'],
            ['name' => 'Dominican Republic', 'iso_code' => 'DO', 'code' => 'DOM', 'region' => 'north-america'],
            ['name' => 'DR Congo', 'iso_code' => 'CD', 'code' => 'COD', 'region' => 'africa'],
            ['name' => 'Ecuador', 'iso_code' => 'EC', 'code' => 'ECU', 'region' => 'south-america'],
            ['name' => 'Egypt', 'iso_code' => 'EG', 'code' => 'EGY', 'region' => 'middle-east'],
            ['name' => 'El Salvador', 'iso_code' => 'SV', 'code' => 'SLV', 'region' => 'north-america'],
            ['name' => 'Equatorial Guinea', 'iso_code' => 'GQ', 'code' => 'GNQ', 'region' => 'africa'],
            ['name' => 'Eritrea', 'iso_code' => 'ER', 'code' => 'ERI', 'region' => 'africa'],
            ['name' => 'Estonia', 'iso_code' => 'EE', 'code' => 'EST', 'region' => 'europe'],
            ['name' => 'Eswatini', 'iso_code' => 'SZ', 'code' => 'SWZ', 'region' => 'africa'],
            ['name' => 'Ethiopia', 'iso_code' => 'ET', 'code' => 'ETH', 'region' => 'africa'],
            ['name' => 'Fiji', 'iso_code' => 'FJ', 'code' => 'FJI', 'region' => 'oceania'],
            ['name' => 'Finland', 'iso_code' => 'FI', 'code' => 'FIN', 'region' => 'europe'],
            ['name' => 'France', 'iso_code' => 'FR', 'code' => 'FRA', 'region' => 'europe'],
            ['name' => 'Gabon', 'iso_code' => 'GA', 'code' => 'GAB', 'region' => 'africa'],
            ['name' => 'Gambia', 'iso_code' => 'GM', 'code' => 'GMB', 'region' => 'africa'],
            ['name' => 'Georgia', 'iso_code' => 'GE', 'code' => 'GEO', 'region' => 'asia'],
            ['name' => 'Germany', 'iso_code' => 'DE', 'code' => 'DEU', 'region' => 'europe'],
            ['name' => 'Ghana', 'iso_code' => 'GH', 'code' => 'GHA', 'region' => 'africa'],
            ['name' => 'Greece', 'iso_code' => 'GR', 'code' => 'GRC', 'region' => 'europe'],
            ['name' => 'Grenada', 'iso_code' => 'GD', 'code' => 'GRD', 'region' => 'north-america'],
            ['name' => 'Guatemala', 'iso_code' => 'GT', 'code' => 'GTM', 'region' => 'north-america'],
            ['name' => 'Guinea', 'iso_code' => 'GN', 'code' => 'GIN', 'region' => 'africa'],
            ['name' => 'Guinea-Bissau', 'iso_code' => 'GW', 'code' => 'GNB', 'region' => 'africa'],
            ['name' => 'Guyana', 'iso_code' => 'GY', 'code' => 'GUY', 'region' => 'south-america'],
            ['name' => 'Haiti', 'iso_code' => 'HT', 'code' => 'HTI', 'region' => 'north-america'],
            ['name' => 'Honduras', 'iso_code' => 'HN', 'code' => 'HND', 'region' => 'north-america'],
            ['name' => 'Hungary', 'iso_code' => 'HU', 'code' => 'HUN', 'region' => 'europe'],
            ['name' => 'Iceland', 'iso_code' => 'IS', 'code' => 'ISL', 'region' => 'europe'],
            ['name' => 'India', 'iso_code' => 'IN', 'code' => 'IND', 'region' => 'asia'],
            ['name' => 'Indonesia', 'iso_code' => 'ID', 'code' => 'IDN', 'region' => 'asia'],
            ['name' => 'Iran', 'iso_code' => 'IR', 'code' => 'IRN', 'region' => 'middle-east'],
            ['name' => 'Iraq', 'iso_code' => 'IQ', 'code' => 'IRQ', 'region' => 'middle-east'],
            ['name' => 'Ireland', 'iso_code' => 'IE', 'code' => 'IRL', 'region' => 'europe'],
            ['name' => 'Israel', 'iso_code' => 'IL', 'code' => 'ISR', 'region' => 'middle-east'],
            ['name' => 'Italy', 'iso_code' => 'IT', 'code' => 'ITA', 'region' => 'europe'],
            ['name' => 'Ivory Coast', 'iso_code' => 'CI', 'code' => 'CIV', 'region' => 'africa'],
            ['name' => 'Jamaica', 'iso_code' => 'JM', 'code' => 'JAM', 'region' => 'north-america'],
            ['name' => 'Japan', 'iso_code' => 'JP', 'code' => 'JPN', 'region' => 'asia'],
            ['name' => 'Jordan', 'iso_code' => 'JO', 'code' => 'JOR', 'region' => 'middle-east'],
            ['name' => 'Kazakhstan', 'iso_code' => 'KZ', 'code' => 'KAZ', 'region' => 'asia'],
            ['name' => 'Kenya', 'iso_code' => 'KE', 'code' => 'KEN', 'region' => 'africa'],
            ['name' => 'Kiribati', 'iso_code' => 'KI', 'code' => 'KIR', 'region' => 'oceania'],
            ['name' => 'Kosovo', 'iso_code' => 'XK', 'code' => 'XKX', 'region' => 'europe'],
            ['name' => 'Kuwait', 'iso_code' => 'KW', 'code' => 'KWT', 'region' => 'middle-east'],
            ['name' => 'Kyrgyzstan', 'iso_code' => 'KG', 'code' => 'KGZ', 'region' => 'asia'],
            ['name' => 'Laos', 'iso_code' => 'LA', 'code' => 'LAO', 'region' => 'asia'],
            ['name' => 'Latvia', 'iso_code' => 'LV', 'code' => 'LVA', 'region' => 'europe'],
            ['name' => 'Lebanon', 'iso_code' => 'LB', 'code' => 'LBN', 'region' => 'middle-east'],
            ['name' => 'Lesotho', 'iso_code' => 'LS', 'code' => 'LSO', 'region' => 'africa'],
            ['name' => 'Liberia', 'iso_code' => 'LR', 'code' => 'LBR', 'region' => 'africa'],
            ['name' => 'Libya', 'iso_code' => 'LY', 'code' => 'LBY', 'region' => 'africa'],
            ['name' => 'Liechtenstein', 'iso_code' => 'LI', 'code' => 'LIE', 'region' => 'europe'],
            ['name' => 'Lithuania', 'iso_code' => 'LT', 'code' => 'LTU', 'region' => 'europe'],
            ['name' => 'Luxembourg', 'iso_code' => 'LU', 'code' => 'LUX', 'region' => 'europe'],
            ['name' => 'Madagascar', 'iso_code' => 'MG', 'code' => 'MDG', 'region' => 'africa'],
            ['name' => 'Malawi', 'iso_code' => 'MW', 'code' => 'MWI', 'region' => 'africa'],
            ['name' => 'Malaysia', 'iso_code' => 'MY', 'code' => 'MYS', 'region' => 'asia'],
            ['name' => 'Maldives', 'iso_code' => 'MV', 'code' => 'MDV', 'region' => 'asia'],
            ['name' => 'Mali', 'iso_code' => 'ML', 'code' => 'MLI', 'region' => 'africa'],
            ['name' => 'Malta', 'iso_code' => 'MT', 'code' => 'MLT', 'region' => 'europe'],
            ['name' => 'Marshall Islands', 'iso_code' => 'MH', 'code' => 'MHL', 'region' => 'oceania'],
            ['name' => 'Mauritania', 'iso_code' => 'MR', 'code' => 'MRT', 'region' => 'africa'],
            ['name' => 'Mauritius', 'iso_code' => 'MU', 'code' => 'MUS', 'region' => 'africa'],
            ['name' => 'Mexico', 'iso_code' => 'MX', 'code' => 'MEX', 'region' => 'north-america'],
            ['name' => 'Micronesia', 'iso_code' => 'FM', 'code' => 'FSM', 'region' => 'oceania'],
            ['name' => 'Moldova', 'iso_code' => 'MD', 'code' => 'MDA', 'region' => 'europe'],
            ['name' => 'Monaco', 'iso_code' => 'MC', 'code' => 'MCO', 'region' => 'europe'],
            ['name' => 'Mongolia', 'iso_code' => 'MN', 'code' => 'MNG', 'region' => 'asia'],
            ['name' => 'Montenegro', 'iso_code' => 'ME', 'code' => 'MNE', 'region' => 'europe'],
            ['name' => 'Morocco', 'iso_code' => 'MA', 'code' => 'MAR', 'region' => 'africa'],
            ['name' => 'Mozambique', 'iso_code' => 'MZ', 'code' => 'MOZ', 'region' => 'africa'],
            ['name' => 'Myanmar', 'iso_code' => 'MM', 'code' => 'MMR', 'region' => 'asia'],
            ['name' => 'Namibia', 'iso_code' => 'NA', 'code' => 'NAM', 'region' => 'africa'],
            ['name' => 'Nauru', 'iso_code' => 'NR', 'code' => 'NRU', 'region' => 'oceania'],
            ['name' => 'Nepal', 'iso_code' => 'NP', 'code' => 'NPL', 'region' => 'asia'],
            ['name' => 'Netherlands', 'iso_code' => 'NL', 'code' => 'NLD', 'region' => 'europe'],
            ['name' => 'New Zealand', 'iso_code' => 'NZ', 'code' => 'NZL', 'region' => 'oceania'],
            ['name' => 'Nicaragua', 'iso_code' => 'NI', 'code' => 'NIC', 'region' => 'north-america'],
            ['name' => 'Niger', 'iso_code' => 'NE', 'code' => 'NER', 'region' => 'africa'],
            ['name' => 'Nigeria', 'iso_code' => 'NG', 'code' => 'NGA', 'region' => 'africa'],
            ['name' => 'North Korea', 'iso_code' => 'KP', 'code' => 'PRK', 'region' => 'asia'],
            ['name' => 'North Macedonia', 'iso_code' => 'MK', 'code' => 'MKD', 'region' => 'europe'],
            ['name' => 'Norway', 'iso_code' => 'NO', 'code' => 'NOR', 'region' => 'europe'],
            ['name' => 'Oman', 'iso_code' => 'OM', 'code' => 'OMN', 'region' => 'middle-east'],
            ['name' => 'Pakistan', 'iso_code' => 'PK', 'code' => 'PAK', 'region' => 'asia'],
            ['name' => 'Palau', 'iso_code' => 'PW', 'code' => 'PLW', 'region' => 'oceania'],
            ['name' => 'Palestine', 'iso_code' => 'PS', 'code' => 'PSE', 'region' => 'middle-east'],
            ['name' => 'Panama', 'iso_code' => 'PA', 'code' => 'PAN', 'region' => 'north-america'],
            ['name' => 'Papua New Guinea', 'iso_code' => 'PG', 'code' => 'PNG', 'region' => 'oceania'],
            ['name' => 'Paraguay', 'iso_code' => 'PY', 'code' => 'PRY', 'region' => 'south-america'],
            ['name' => 'Peru', 'iso_code' => 'PE', 'code' => 'PER', 'region' => 'south-america'],
            ['name' => 'Philippines', 'iso_code' => 'PH', 'code' => 'PHL', 'region' => 'asia'],
            ['name' => 'Poland', 'iso_code' => 'PL', 'code' => 'POL', 'region' => 'europe'],
            ['name' => 'Portugal', 'iso_code' => 'PT', 'code' => 'PRT', 'region' => 'europe'],
            ['name' => 'Qatar', 'iso_code' => 'QA', 'code' => 'QAT', 'region' => 'middle-east'],
            ['name' => 'Romania', 'iso_code' => 'RO', 'code' => 'ROU', 'region' => 'europe'],
            ['name' => 'Russia', 'iso_code' => 'RU', 'code' => 'RUS', 'region' => 'europe'],
            ['name' => 'Rwanda', 'iso_code' => 'RW', 'code' => 'RWA', 'region' => 'africa'],
            ['name' => 'Saint Kitts and Nevis', 'iso_code' => 'KN', 'code' => 'KNA', 'region' => 'north-america'],
            ['name' => 'Saint Lucia', 'iso_code' => 'LC', 'code' => 'LCA', 'region' => 'north-america'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VC', 'code' => 'VCT', 'region' => 'north-america'],
            ['name' => 'Samoa', 'iso_code' => 'WS', 'code' => 'WSM', 'region' => 'oceania'],
            ['name' => 'San Marino', 'iso_code' => 'SM', 'code' => 'SMR', 'region' => 'europe'],
            ['name' => 'Sao Tome and Principe', 'iso_code' => 'ST', 'code' => 'STP', 'region' => 'africa'],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SA', 'code' => 'SAU', 'region' => 'middle-east'],
            ['name' => 'Senegal', 'iso_code' => 'SN', 'code' => 'SEN', 'region' => 'africa'],
            ['name' => 'Serbia', 'iso_code' => 'RS', 'code' => 'SRB', 'region' => 'europe'],
            ['name' => 'Seychelles', 'iso_code' => 'SC', 'code' => 'SYC', 'region' => 'africa'],
            ['name' => 'Sierra Leone', 'iso_code' => 'SL', 'code' => 'SLE', 'region' => 'africa'],
            ['name' => 'Singapore', 'iso_code' => 'SG', 'code' => 'SGP', 'region' => 'asia'],
            ['name' => 'Slovakia', 'iso_code' => 'SK', 'code' => 'SVK', 'region' => 'europe'],
            ['name' => 'Slovenia', 'iso_code' => 'SI', 'code' => 'SVN', 'region' => 'europe'],
            ['name' => 'Solomon Islands', 'iso_code' => 'SB', 'code' => 'SLB', 'region' => 'oceania'],
            ['name' => 'Somalia', 'iso_code' => 'SO', 'code' => 'SOM', 'region' => 'africa'],
            ['name' => 'South Africa', 'iso_code' => 'ZA', 'code' => 'ZAF', 'region' => 'africa'],
            ['name' => 'South Korea', 'iso_code' => 'KR', 'code' => 'KOR', 'region' => 'asia'],
            ['name' => 'South Sudan', 'iso_code' => 'SS', 'code' => 'SSD', 'region' => 'africa'],
            ['name' => 'Spain', 'iso_code' => 'ES', 'code' => 'ESP', 'region' => 'europe'],
            ['name' => 'Sri Lanka', 'iso_code' => 'LK', 'code' => 'LKA', 'region' => 'asia'],
            ['name' => 'Sudan', 'iso_code' => 'SD', 'code' => 'SDN', 'region' => 'africa'],
            ['name' => 'Suriname', 'iso_code' => 'SR', 'code' => 'SUR', 'region' => 'south-america'],
            ['name' => 'Sweden', 'iso_code' => 'SE', 'code' => 'SWE', 'region' => 'europe'],
            ['name' => 'Switzerland', 'iso_code' => 'CH', 'code' => 'CHE', 'region' => 'europe'],
            ['name' => 'Syria', 'iso_code' => 'SY', 'code' => 'SYR', 'region' => 'middle-east'],
            ['name' => 'Taiwan', 'iso_code' => 'TW', 'code' => 'TWN', 'region' => 'asia'],
            ['name' => 'Tajikistan', 'iso_code' => 'TJ', 'code' => 'TJK', 'region' => 'asia'],
            ['name' => 'Tanzania', 'iso_code' => 'TZ', 'code' => 'TZA', 'region' => 'africa'],
            ['name' => 'Thailand', 'iso_code' => 'TH', 'code' => 'THA', 'region' => 'asia'],
            ['name' => 'Timor-Leste', 'iso_code' => 'TL', 'code' => 'TLS', 'region' => 'asia'],
            ['name' => 'Togo', 'iso_code' => 'TG', 'code' => 'TGO', 'region' => 'africa'],
            ['name' => 'Tonga', 'iso_code' => 'TO', 'code' => 'TON', 'region' => 'oceania'],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TT', 'code' => 'TTO', 'region' => 'north-america'],
            ['name' => 'Tunisia', 'iso_code' => 'TN', 'code' => 'TUN', 'region' => 'africa'],
            ['name' => 'Turkey', 'iso_code' => 'TR', 'code' => 'TUR', 'region' => 'middle-east'],
            ['name' => 'Turkmenistan', 'iso_code' => 'TM', 'code' => 'TKM', 'region' => 'asia'],
            ['name' => 'Tuvalu', 'iso_code' => 'TV', 'code' => 'TUV', 'region' => 'oceania'],
            ['name' => 'Uganda', 'iso_code' => 'UG', 'code' => 'UGA', 'region' => 'africa'],
            ['name' => 'Ukraine', 'iso_code' => 'UA', 'code' => 'UKR', 'region' => 'europe'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'AE', 'code' => 'ARE', 'region' => 'middle-east'],
            ['name' => 'United Kingdom', 'iso_code' => 'GB', 'code' => 'GBR', 'region' => 'europe'],
            ['name' => 'United States', 'iso_code' => 'US', 'code' => 'USA', 'region' => 'north-america'],
            ['name' => 'Uruguay', 'iso_code' => 'UY', 'code' => 'URY', 'region' => 'south-america'],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZ', 'code' => 'UZB', 'region' => 'asia'],
            ['name' => 'Vanuatu', 'iso_code' => 'VU', 'code' => 'VUT', 'region' => 'oceania'],
            ['name' => 'Vatican City', 'iso_code' => 'VA', 'code' => 'VAT', 'region' => 'europe'],
            ['name' => 'Venezuela', 'iso_code' => 'VE', 'code' => 'VEN', 'region' => 'south-america'],
            ['name' => 'Vietnam', 'iso_code' => 'VN', 'code' => 'VNM', 'region' => 'asia'],
            ['name' => 'Yemen', 'iso_code' => 'YE', 'code' => 'YEM', 'region' => 'middle-east'],
            ['name' => 'Zambia', 'iso_code' => 'ZM', 'code' => 'ZMB', 'region' => 'africa'],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZW', 'code' => 'ZWE', 'region' => 'africa'],
        ];
    }

    public static function names(): array
    {
        return array_column(self::all(), 'name');
    }

    public static function flagEmoji(string $iso): string
    {
        $iso = strtoupper($iso);
        if (strlen($iso) !== 2) {
            return '🏳️';
        }
        $chars = str_split($iso);

        return mb_chr(ord($chars[0]) + 127397) . mb_chr(ord($chars[1]) + 127397);
    }

    public static function flagUrl(?string $iso, int $width = 40): ?string
    {
        $iso = strtolower((string) $iso);
        if (strlen($iso) !== 2) {
            return null;
        }

        return "https://flagcdn.com/w{$width}/{$iso}.png";
    }
}
